course_name = "软体机器人理论与技术"
course_code = "EMEC1010"
repo_type = "normal"
description = """\nAuto bootstrap by pr-server for missing course target.\n"""

[[sections]]
title = "课程信息"
[[sections.items]]
content = """

初始化课程条目。

"""
[[sections]]
title = "1"
[[sections.items]]
content = "1"
author = { name = "1", link = "1", date = "2026-04" }