course_name = "博弈论"
course_code = "ECON3001"
repo_type = "normal"
description = """\nAuto bootstrap by pr-server for missing course target.\n"""

[[sections]]
title = "课程信息"
[[sections.items]]
content = """

初始化课程条目。

"""
[[sections]]
title = "考核"
[[sections.items]]
content = """
两次作业，或为期末题目来源
作业40%
期末60%
*题目，课件均英文，答案允许中文
"""
author = { name = "111", link = "", date = "2026-07" }